---
swagger: "2.0"
info:
  description: ""
  version: "1.6.0"
  title: "theurbanwild"
  contact:
    name: "alicedigitallabs@gmail.com"
    email: "alicedigitallabs@gmail.com"
host: "urbanwilddbapi.herokuapp.com"
schemes:
- "https"
paths:
  /events/:
    get:
      tags:
      - "wildlifelog"
      description: "Loads a list of Event"
      operationId: "getEvents"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "$page"
        in: "query"
        required: false
        type: "string"
        description: "Number of the page to retrieve. Integer value."
        x-example: "sample $page"
      - name: "lat"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ lat"
        x-example: "sample lat"
      - name: "lon"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ lon"
        x-example: "sample lon"
      - name: "date"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ date"
        x-example: "sample date"
      - name: "id"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ id"
        x-example: "sample id"
      - name: "$size"
        in: "query"
        required: false
        type: "string"
        description: "Size of the page to retrieve. Integer value"
        x-example: "sample $size"
      - name: "postcode"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ postcode"
        x-example: "sample postcode"
      - name: "thing"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ thing"
        x-example: "sample thing"
      - name: "$sort"
        in: "query"
        required: false
        type: "string"
        description: "Order in which to retrieve the results. Multiple sort criteria\
          \ can be passed. Example: sort=age ASC,height DESC"
        x-example: "sample $sort"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        400:
          description: "Status 400"
    post:
      tags:
      - "wildlifelog"
      description: "Adds a Event"
      operationId: "postEvents"
      consumes:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Event"
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Event"
  /events/{eventid}:
    get:
      tags:
      - "wildlifelog"
      description: "Loads a Event"
      operationId: "getEventsEventid"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "Status 400"
    put:
      tags:
      - "wildlifelog"
      description: "Stores a Event"
      operationId: "putEventsEventid"
      consumes:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Event"
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Event"
    delete:
      tags:
      - "wildlifelog"
      description: "Deletes a Event"
      operationId: "deleteEventsEventid"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "eventid"
      in: "path"
      required: true
      type: "string"
      description: "Identifier of the Event"
      x-example: "sample eventid"
  /things/:
    get:
      tags:
      - "wildlifelog"
      description: "Loads a list of Thing"
      operationId: "getThings"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "$size"
        in: "query"
        required: false
        type: "string"
        description: "Size of the page to retrieve. Integer value"
        x-example: "sample $size"
      - name: "id"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ id"
        x-example: "sample id"
      - name: "$sort"
        in: "query"
        required: false
        type: "string"
        description: "Order in which to retrieve the results. Multiple sort criteria\
          \ can be passed. Example: sort=age ASC,height DESC"
        x-example: "sample $sort"
      - name: "name"
        in: "query"
        required: false
        type: "string"
        description: "Allows to filter the collections of result by the value of field\
          \ name"
        x-example: "sample name"
      - name: "$page"
        in: "query"
        required: false
        type: "string"
        description: "Number of the page to retrieve. Integer value."
        x-example: "sample $page"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Thing"
        400:
          description: "Status 400"
    post:
      tags:
      - "wildlifelog"
      description: "Adds a Thing"
      operationId: "postThings"
      consumes:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Thing"
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Thing"
  /things/{thingid}:
    get:
      tags:
      - "wildlifelog"
      description: "Loads a Thing"
      operationId: "getThingsThingid"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Thing"
        400:
          description: "Status 400"
    put:
      tags:
      - "wildlifelog"
      description: "Stores a Thing"
      operationId: "putThingsThingid"
      consumes:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Thing"
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Thing"
    delete:
      tags:
      - "wildlifelog"
      description: "Deletes a Thing"
      operationId: "deleteThingsThingid"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "thingid"
      in: "path"
      required: true
      type: "string"
      description: "Identifier of the Thing"
      x-example: "sample thingid"
definitions:
  Event:
    type: "object"
    required:
    - "date"
    - "id"
    - "lat"
    - "lon"
    - "postcode"
    - "thing"
    properties:
      id:
        type: "string"
        description: "Auto-generated primary key field"
        example: "sample id"
      postcode:
        type: "string"
        example: "M1 5GD"
      date:
        type: "integer"
        format: "int64"
        example: 1511395200000
      thing:
        type: "string"
        description: "This property is a reference to a Thing"
        example: "sample thing"
      lat:
        type: "number"
        format: "double"
        example: 1.1
      lon:
        type: "number"
        format: "double"
        example: 1.1
    example: "{\"id\":\"sample id\",\"postcode\":\"M1 5GD\",\"date\":1511395200000,\"\
      thing\":\"sample thing\",\"lat\":1.1,\"lon\":1.1}"
  Thing:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        description: "Auto-generated primary key field"
        example: "sample id"
      name:
        type: "string"
        example: "Jay"
    example: "{\"id\":\"sample id\",\"name\":\"Jay\"}"
